version: '3.6'

services:
  portainer:
    image: portainer/portainer:1.18.1
    container_name: portainer
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
